[dependencies]
base = "0.8.3"
xtended-numbers = "0.2.0"

[package]
name = "candid"
version = "1.0.2"
description = "A Candid library for encoding and decoding candid bytes"
repository = "https://github.com/edjcase/motoko_candid"

[dev-dependencies]
test = "1.0.1"
